#!/bin/bash
set -e

# Copy a default configuration into place if not present
if ! [ -f /etc/nginx/nginx.conf ]; then
  cp -upR "/usr/local/openresty/nginx/conf/." "/etc/nginx/"
  echo "daemon off;" >> "/etc/nginx/nginx.conf"
fi

command="$@"

${command}
